#Resources:
#Material list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#EntityType list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html (Only use living entities, e.g. do not use 'ARROW')
#Color list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
#Particle list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#
#
#The link to the resource pack (make sure that it is an auto-download link, e.g. a dropbox-link should end on "?dl=1")
resourcepack: 'https://www.dropbox.com/sh/rl6uk9su0eenmfy/AACf4JRXb2kYv7COAsU276-Oa?dl=1'
#Core-Items
cores:
  fullcore:
    name: '§dFull Core'
    item: GOLDEN_HOE
    customModelData: 1111111
    crafting: 8
    enchanted: false
  piece:
    name: '§dCore Piece'
    item: GOLDEN_HOE
    customModelData: 1111112
    crafting: 8
    enchanted: false
  shard:
    name: '§dCore Shard'
    item: GOLDEN_HOE
    customModelData: 1111113
    enchanted: false
    babyDrop: true
    #The order of the mobs doesn't affect the plugin
    mobDroprate:
      #Passive mobs
      AXOLOTL: 0
      BAT: 0
      CAT: 0
      CHICKEN: 0
      COD: 0
      COW: 0
      DONKEY: 0
      FOX: 0
      GLOW_SQUID: 0
      HORSE: 0
      MUSHROOM_COW: 0
      MULE: 0
      OCELOT: 0
      PARROT: 0
      PIG: 0
      PUFFERFISH: 0
      RABBIT: 0
      SALMON: 0
      SHEEP: 0
      SKELETON_HORSE: 0
      SNOW_GOLEM: 0
      SQUID: 0
      STRIDER: 0
      TROPICAL_FISH: 0
      TURTLE: 0
      VILLAGER: 0
      WANDERING_TRADER: 0
      #Neutral mobs
      BEE: 0.1
      DOLPHIN: 0.1
      GOAT: 0.1
      IRON_GOLEM: 0.1
      LLAMA: 0.1
      PIGLIN: 0.1
      PANDA: 0.1
      POLAR_BEAR: 0.1
      WOLF: 0.1
      ZOMBIEFIED_PIGLIN: 0.1
      #Hostile mobs
      BLAZE: 0.1
      CREEPER: 0.1
      DROWNED: 0.1
      ELDER_GUARDIAN: 0.1
      ENDERMAN: 0.1
      ENDERMITE: 0.1
      EVOKER: 0.1
      GHAST: 0.1
      GUARDIAN: 0.1
      HOGLIN: 0.1
      HUSK: 0.1
      MAGMA_CUBE: 0.1
      PHANTOM: 0.1
      PIGLIN_BRUTE: 0.1
      PILLAGER: 0.1
      RAVAGER: 0.1
      SHULKER: 0.1
      SILVERFISH: 0.1
      SKELETON: 0.1
      SLIME: 0.1
      SPIDER: 0.1
      STRAY: 0.1
      VEX: 0.1
      VINDICATOR: 0.1
      WITCH: 0.1
      WITHER_SKELETON: 0.1
      ZOGLIN: 0.1
      ZOMBIE: 0.1
      ZOMBIE_VILLAGRE: 0.1
eggs:
  #The name (not the ingame name) should be all lower case without spaces (e.g. explosive_chicken instead of Explosive Chicken)
  explosive_chicken:
    name: "§cExplosive Chicken"
    item: "CHICKEN_SPAWN_EGG"
    enchanted: true
    throwable: true
    #If it's throwable
    glow: true
    glowColor: "blue"
    #
    amountFromCrafting: 1
    #Use 'fullcore', 'piece' or 'shard' for those items
    #Ingredient should be a single letter
    ingredients:
      A: "fullcore"
      B: "FEATHER"
      C: "IRON_INGOT"
    recipe:
      row1: "BCB"
      row2: "CAC"
      row3: "BCB"
    spawnedEntity: "explosive_chicken"
    amount: 3
mobs:
  #Mobs should be unique
  explosive_chicken:
    name: "§cExplosive Chicken"
    type: "chicken"
    glow: true
    glowColor: "red"
    health: 50
    speed: 1
    multiRemote: true
    dropsOnDeath: true
    #
    #Explosion settings
    #
    #Set to 0 to disable
    explosionRadius: 5
    explosionDamage: 5
    explosionPotion: "SLOW"
    #In ticks (1 second is usually 20 ticks)
    explosionPotionDuration: 10
    explosionPotionAmplifier: 2
    #Knockback
    explosionPower: 3
    #Set to 0 to disable
    lavaRadius: 1
    #How long the damaged Entity should burn (in Ticks)
    fireExplosion: 0
    #Set to 1 to destroy every block in range, set to 0 to turn off breaking blocks
    explosionBreakBlockChance: 0.9
    #If Blocks should drop loot (usually an explosion drops every second block)
    #Keep in mind that blocks will only be broken depending on explosionBreakBlockChance
    #e.g. if explosionBreakBlockChance and explosionDropBlockChance are both set to 0.5
    #every 4th block will drop loot
    explosionDropBlockChance: 0.5
    dontBreak: "BARRIER,COMMAND_BLOCK,END_PORTAL_FRAME,OBSIDIAN,BEDROCK"
    #In ticks (1 second is usually 20 ticks)
    #Set to 0 for no explosion
    explosionTimer: 300
    #Set to 0 to turn of flashbang
    explosionFlashRange: 5
    #seconds
    explosionFlashDuration: 40
    explosionFlashOwner: true
    #
    #Passive abilities:
    #
    randomStroll: true
    strollSpeed: 1
    #
    #Entity type for specific entity, "all" for all and, "none" for none
    attackEntities: "ZOMBIE,SKELETON"
    #"melee", "range" or "creeper"
    attackType: "range"
    attackDamage: 5
    #attackSpeed * 5 Ticks till next attack (use Integers only)
    attackSpeed: 2
    attackRange: 10
    walkToTargetSpeed: 1.3
    attackTriggerRange: 30
    multiAttack: false
    #How long the attacked entity should burn (in Ticks)
    fireAttack: 100
    #
    #Material for specific blocks, "all" for all and, "none" for none
    breakBlocks: "OBSIDIAN,DIAMOND_BLOCK"
    #0-10 (0 = moves to block without damaging it; 10 = breaks one hit)
    breakDamage: 1
    #breakSpeed * 5 Ticks till next attack (1 = 1/4 second; use Integers only)
    breakSpeed: 1
    walkToBlockSpeed: 1.2
    #This method has a runtime of O(n^3), be careful with big numbers
    breakTriggerRange: 15
    multiBreak: false
    prioritizeBlocks: false
    #How many blocks till mob stops
    maxBlocks: 10
    #0: right click; 1: left click; 2: shift right click; 3: shift left click
    #"M" for movement and "A" for attack
    abilities:
      0:
        type: "M"
        ability: "walk_to_spot"
      1:
        type: "M"
        ability: "jump"
      2:
        type: "A"
        ability: "sweep_attack"
      3:
        type: "M"
        ability: "search_sand"

movementAbilities:
  walk_to_spot:
    name: "§aWalk to Click"
    #In Ticks
    cooldown: 0
    #Max range of the remote to the mob and the clicked locations
    maxDistClick: 50
    maxDistMob: 50
    #clicked location: "clicked", entity (specify below): "entity", block (specify below): "block", no ai movement: "none"
    goTo: "clicked"
    #If you put "none" for goTo the 4 options below are unnecessary
    entities: "none"
    blocks: "none"
    range: 10
    speed: 1.1
    #Delay for goTo in ticks (if you set a velocity you may need a delay to make the navigation work)
    delay: 0
    #
    #"x,y,z", "x~" for x-times the direction the mob is facing (e.g. 0.2~,1,0.2~) and "x*" for x-times the current velocity (e.g. 1*,1,1*)
    #Use decimals before "~" or "*" even if the number is even (e.g. 1.0*,2.0~,1)
    velocity: "0,0,0"
    particle: "DRAGON_BREATH"
    particleAmount: 10
  jump:
    name: "§aJump"
    #In Ticks
    cooldown: 30
    #Max range of the remote to the mob and the clicked locations
    maxDistClick: 50
    maxDistMob: 50
    #clicked location: "clicked", entity (specify below): "entity", block (specify below): "block", no ai movement: "none"
    goTo: "none"
    #If you put "none" for goTo the 4 options below are unnecessary (Don't remove, just put anything)
    entities: "none"
    blocks: "none"
    range: 10
    speed: 1.1
    #Delay for goTo in ticks (if you set a velocity you may need a delay for the navigation to work)
    delay: 5
    #
    #"x,y,z", "x~" for x-times the direction the mob is facing (e.g. 0.2~,1,0.2~) and "x*" for x-times the current velocity (e.g. 1.0*,1,1.0*)
    #Use decimals before "~" or "*" even if the number is even (e.g. 1.0*,2.0~,1)
    velocity: "0.2*,1,0.2*"
    particle: "DRAGON_BREATH"
    particleAmount: 10
  search_sand:
    name: "§aSearch Sand"
    #In Ticks
    cooldown: 50
    #Max range of the remote to the mob and the clicked locations
    maxDistClick: 0
    maxDistMob: 50
    #clicked location: "clicked", entity (specify below): "entity", block (specify below): "block", no ai movement: "none"
    goTo: "block"
    #If you put "none" for goTo the 4 options below are unnecessary (Don't remove, just put anything)
    entities: "none"
    blocks: "SAND"
    range: 20
    speed: 1.3
    #Delay for goTo in ticks (if you set a velocity you may need a delay for the navigation to work)
    delay: 0
    #
    #"x,y,z", "x~" for x-times the direction the mob is facing (e.g. 0.2~,1,0.2~) and "x*" for x-times the current velocity (e.g. 1*,1,1*)
    #Use decimals before "~" or "*" even if the number is even (e.g. 1.0*,2.0~,1)
    velocity: "0,0,0"
    particle: "BUBBLE_POP"
    particleAmount: 10
attackAbilities:
  sweep_attack:
    name: "§aSweep Attack"
    #In Ticks
    cooldown: 100
    #Max range of the remote to the mob
    maxDistMob: 50
    #"all", "none" or <entity1,entity2,...>
    entities: "all"
    damage: 15
    range: 5
    fire: 100
    multi: true
    knockback: 3
    #Damage delay
    delay: 10
    #"x,y,z", "x~" for x-times the direction the mob is facing (e.g. 0.2~,1,0.2~) and "x*" for x-times the current velocity (e.g. 1*,1,1*)
    #Use decimals before "~" or "*" even if the number is even (e.g. 1.0*,2.0~,1)
    velocity: "0,0.3,0"
    particle: "FLASH"
    particleAmount: 10