#Resources:
#Material list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#EntityType list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html (Only use living entities, e.g. do not use 'ARROW')
#
#
#
#The link to the resource pack (make sure that it is an auto-download link, e.g. a dropbox-link should end on "?dl=1")
resourcepack: 'https://www.dropbox.com/sh/rl6uk9su0eenmfy/AACf4JRXb2kYv7COAsU276-Oa?dl=1'
#Core-Items
cores:
  fullcore:
    name: '§dFull Core'
    item: GOLDEN_HOE
    customModelData: 1111111
    crafting: 8
    enchanted: false
  piece:
    name: '§dCore Piece'
    item: GOLDEN_HOE
    customModelData: 1111112
    crafting: 8
    enchanted: false
  shard:
    name: '§dCore Shard'
    item: GOLDEN_HOE
    customModelData: 1111113
    enchanted: false
    babyDrop: true
    #The order of the mobs doesn't affect the plugin
    mobDroprate:
      #Passive mobs
      AXOLOTL: 0
      BAT: 0
      CAT: 0
      CHICKEN: 0
      COD: 0
      COW: 0
      DONKEY: 0
      FOX: 0
      GLOW_SQUID: 0
      HORSE: 0
      MUSHROOM_COW: 0
      MULE: 0
      OCELOT: 0
      PARROT: 0
      PIG: 0
      PUFFERFISH: 0
      RABBIT: 0
      SALMON: 0
      SHEEP: 0
      SKELETON_HORSE: 0
      SNOW_GOLEM: 0
      SQUID: 0
      STRIDER: 0
      TROPICAL_FISH: 0
      TURTLE: 0
      VILLAGER: 0
      WANDERING_TRADER: 0
      #Neutral mobs
      BEE: 0.1
      DOLPHIN: 0.1
      GOAT: 0.1
      IRON_GOLEM: 0.1
      LLAMA: 0.1
      PIGLIN: 0.1
      PANDA: 0.1
      POLAR_BEAR: 0.1
      WOLF: 0.1
      ZOMBIEFIED_PIGLIN: 0.1
      #Hostile mobs
      BLAZE: 0.1
      CREEPER: 0.1
      DROWNED: 0.1
      ELDER_GUARDIAN: 0.1
      ENDERMAN: 0.1
      ENDERMITE: 0.1
      EVOKER: 0.1
      GHAST: 0.1
      GUARDIAN: 0.1
      HOGLIN: 0.1
      HUSK: 0.1
      MAGMA_CUBE: 0.1
      PHANTOM: 0.1
      PIGLIN_BRUTE: 0.1
      PILLAGER: 0.1
      RAVAGER: 0.1
      SHULKER: 0.1
      SILVERFISH: 0.1
      SKELETON: 0.1
      SLIME: 0.1
      SPIDER: 0.1
      STRAY: 0.1
      VEX: 0.1
      VINDICATOR: 0.1
      WITCH: 0.1
      WITHER_SKELETON: 0.1
      ZOGLIN: 0.1
      ZOMBIE: 0.1
      ZOMBIE_VILLAGRE: 0.1
eggs:
  #The name (not the ingame name) should be all lower case without spaces (e.g. explosive_chicken instead of Explosive Chicken)
  #It will be used as an id and should therefore be unique
  explosive_chicken:
    name: "§cExplosive Chicken"
    item: "CHICKEN_SPAWN_EGG"
    enchanted: true
    throwable: true
    amountFromCrafting: 1
    #Use 'fullcore', 'piece' or 'shard' for those items
    #Ingredient should be a single letter
    ingredients:
      A: "fullcore"
      B: "FEATHER"
      C: "IRON_INGOT"
    recipe:
      row1: "BCB"
      row2: "CAC"
      row3: "BCB"
    spawnedEntity: "explosive_chicken"
    amount: 1
mobs:
  #Mobs should be unique
  explosive_chicken:
    name: "§cExplosive Chicken"
    type: "chicken"
    health: 50
    speed: 1
    multiRemote: true
    dropsOnDeath: true
    #
    #Explosion settings
    #
    dropsOnExplosion: false
    #Set to 0 to disable
    explosionRadius: 5
    explosionDamage: 5
    explosionPotion: "JUMP"
    #In ticks (1 second is usually 20 ticks)
    explosionPotionDuration: 10
    explosionPotionAmplifier: 2
    #Knockback
    explosionPower: 3
    #Set to 0 to disable
    lavaRadius: 1
    #Set to 1 to destroy every block in range, set to 0 to turn off breaking blocks
    explosionBreakBlockChance: 0.9
    #If Blocks should drop loot (usually an explosion drops every second block)
    #Keep in mind that blocks will only be broken depending on explosionBreakBlockChance
    #e.g. if explosionBreakBlockChance and explosionDropBlockChance are both set to 0.5
    #every 4th block will drop loot
    explosionDropBlockChance: 0.5
    #In ticks (1 second is usually 20 ticks)
    #Set to 0 for no explosion
    explosionTimer: 100
    #
    #Passive abilities:
    #
    randomStroll: true
    strollSpeed: 1
    #
    #Entity type for specific entity, "all" for all and, "none" for none
    attackEntities: "ZOMBIE,SKELETON"
    attackDamage: 5
    #attackSpeed * 5 Ticks till next attack (use Integers only)
    attackSpeed: 2
    walkToTargetSpeed: 1.3
    attackTriggerRange: 15
    multiAttack: false
    #
    #Material for specific blocks, "all" for all and, "none" for none
    breakBlocks: "OBSIDIAN,DIAMOND_BLOCK"
    #0-10 (0 = moves to block without damaging it; 10 = breaks one hit)
    breakDamage: 1
    #breakSpeed * 5 Ticks till next attack (1 = 1/4 second; use Integers only)
    breakSpeed: 1
    walktToBlockSpeed: 1.2
    #This method has a runtim of O(n^3), be careful with big numbers
    breakTriggerRange: 15
    multiBreak: false
    prioritizeBlocks: false

activeAbilities:
  #Abilities should be unique
  walk_to_spot:
    name: "§aWalk to Click"
    #0: right click; 1: left click; 2: shift right click; 3: shift left click
    key: 0
    #Max range of the remote to the mob and the clicked locations
    maxDistClick: 50
    maxDistMob: 20
    #clicked location: "clicked", entity (specify below): "entity", blocktype: "block"
    goTo: "clicked"

